apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-gitops
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/ArgoCD101-GuestbookGitOps/
    repoURL: https://github.com/pallamidessi/ArgoCDRollouts
